### ISSUE TITLE
Normalize the section elements

### ISSUE THREAD

**Issue by lucascono** [lucascono/framework#10]
```css
/**
 * Remove the margin in all browsers (opinionated).
 */

body {
  margin: 0;
}

/**
 * Add the correct display in IE 9-.
 */

article,
aside,
footer,
header,
nav,
section {
  display: block;
}
```
