### ISSUE TITLE
Apply system fonts to the root element

### ISSUE THREAD

**Issue by lucascono** [lucascono/framework#2]
```css
html {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif
}
```

More info in [bitsofcode](https://bitsofco.de/the-new-system-font-stack/)
