### ISSUE TITLE
Apply colors of material in the root element

### ISSUE THREAD

**Issue by lucascono** [lucascono/framework#3]
```css
html {
  background: #fafafa;
  color: rgba(0, 0, 0, 0.87);
}
```

More info in [material](https://material.google.com/style/color.html#color-text-background-colors)
