### ISSUE TITLE
Reset the box-sizing property from the root element

### ISSUE THREAD

**Issue by lucascono** [lucascono/framework#4]
```css
html {
  box-sizing: border-box;
}

*, *::before, *::after {
  box-sizing: inherit;
}
```

More info in [css-tricks](https://css-tricks.com/box-sizing/)
