### ISSUE TITLE
Add configuration variables for the root element

### ISSUE THREAD

**Issue by lucascono** [lucascono/framework#5]
```scss
$font-family-system: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif !default;

$theme-dark: false !default;

$dark-theme-background-primary: #303030 !default;
$dark-theme-background-secondary: #424242 !default;

$dark-theme-color-primary: rgba(255, 255, 255, 1.0) !default;
$dark-theme-color-secondary: rgba(255, 255, 255, 0.70) !default;
$dark-theme-color-dimmed: rgba(255, 255, 255, 0.50) !default;
$dark-theme-color-divider: rgba(255, 255, 255, 0.12) !default;

$light-theme-background-primary: #fafafa !default;
$light-theme-background-secondary: #ffffff !default;

$light-theme-color-primary: rgba(0, 0, 0, 0.87) !default;
$light-theme-color-secondary: rgba(0, 0, 0, 0.54) !default;
$light-theme-color-dimmed: rgba(0, 0, 0, 0.38) !default;
$light-theme-color-divider: rgba(0, 0, 0, 0.12) !default;

$document-background: if($theme-dark, $dark-theme-background-primary, $light-theme-background-primary) !default;
$document-color: if($theme-dark, $dark-theme-color-primary, $light-theme-color-primary) !default;
$document-font-family: $font-family-system !default;

$reset-box-sizing: true;

html {
  background: $document-background;
  color: $document-color;
  font-family: $document-font-family;

  @if $reset-box-sizing {
    box-sizing: border-box;
  }
}

@if $reset-box-sizing {
  *, *::before, *::after {
    box-sizing: inherit;
  }
}
```
