### ISSUE TITLE
Add option to reset the line-height to the root element

### ISSUE THREAD

**Issue by lucascono** [lucascono/framework#8]
```scss
$reset-line-height: true;

html {
  line-height: if($reset-line-height, 1, 1.15);
}
```
